// ─── What is this file? ──────────────────────────────────────────────────────
//
// String templates for all generated files.
// Keeping them here (not inline in command files) makes them easy to read,
// test, and update independently of the logic that writes them to disk.

use crate::manifest::{AuthSetting, FrontendFramework};

// ─── sweech init templates ────────────────────────────────────────────────────

pub fn manifest_toml(project_name: &str) -> String {
    format!(
        r#"[project]
name = "{project_name}"
version = "0.1.0"

[build]
mode = "monolith"
runtime = "rust"
port = 3000

[[applet]]
name = "hello"
path = "hello.applet"
auth = "public"

# ── Add more applets below ──────────────────────────────────────────────────
# [[applet]]
# name = "products"
# path = "products.applet"
# auth = "required"
# guards = []

# ── Frontends ────────────────────────────────────────────────────────────────
# [[frontend]]
# name = "web"
# path = "apps/web"
# framework = "next"
# deploy_target = "^build"
# serve = "embedded"
# dev_command = "npm run dev"
# build_command = "npm run build"
# port = 3001

[http]
timeout_ms = 30000
"#
    )
}

/// Single root Cargo.toml — workspace + package combined.
/// No separate app crate needed. sweech.app.rs lives at the root
/// alongside .applet dirs, so #[path = "./hello.applet/route.rs"] works.
pub fn root_cargo_toml(project_name: &str, sweech_core_dep: &str, sweech_axum_dep: &str) -> String {
    format!(
        r#"[workspace]
resolver = "3"

[package]
name = "{project_name}"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "{project_name}"
path = "sweech.app.rs"

[dependencies]
sweech-core = {sweech_core_dep}
sweech-axum = {sweech_axum_dep}
axum = "0.7"
tokio = {{ version = "1", features = ["full"] }}
serde = {{ version = "1", features = ["derive"] }}
serde_json = "1"
async-trait = "0.1"
"#
    )
}

/// Kept for compatibility — delegates to root_cargo_toml.
/// Will be removed once all call sites are updated.
#[allow(dead_code)]
pub fn workspace_cargo_toml(
    project_name: &str,
    sweech_core_dep: &str,
    sweech_axum_dep: &str,
) -> String {
    root_cargo_toml(project_name, sweech_core_dep, sweech_axum_dep)
}

#[allow(dead_code)]
pub fn app_cargo_toml(_project_name: &str) -> String {
    String::new() // no longer used
}

pub fn sweech_app_rs(project_name: &str) -> String {
    let pascal = to_pascal_case(project_name);
    format!(
        r#"//! {project_name} — application entry point
//!
//! Generated by `sweech init`. Do not rename this file.
//!
//! HOW APPLET IMPORTS WORK
//! ─────────────────────────────────────────────────────────────────────────
//! Each .applet directory contains route.rs files that implement the Handler
//! trait. Import them using Rust's #[path] attribute to reach files that
//! live outside this crate's src/ directory:
//!
//!   #[path = "./inventory.applet/items/route.rs"]
//!   mod inventory_items;
//!   use inventory_items::GetItems;
//!
//! `sweech build` will generate this wiring automatically in a future version.
//! ─────────────────────────────────────────────────────────────────────────

use sweech_axum::{{Applet, AppletConfig, SweechApp}};
use sweech_axum::middleware::{{AuthState, AuthValidator}};
use sweech_axum::RequestParts;
use sweech_axum::router::{{AppState, AppletRouter}};
use sweech_core::auth::{{AuthRequirement, UserClaims}};
use std::sync::Arc;
use async_trait::async_trait;
use tokio::net::TcpListener;

// ── Applet handler imports ────────────────────────────────────────────────────

#[path = "./hello.applet/route.rs"]
mod hello_route;
use hello_route::Hello;

// ─── Auth middleware ──────────────────────────────────────────────────────────
//
// Replace with your real JWT / session validation logic.
// Return Some(UserClaims) when the token is valid, None otherwise.
// Runs on every request before any handler or guard.

struct {pascal}Auth;

#[async_trait]
impl AuthValidator for {pascal}Auth {{
    async fn validate(&self, _parts: &RequestParts) -> Option<UserClaims> {{
        // TODO: implement token validation
        // Example JWT:
        //   let token = _parts.headers.get("authorization")?.to_str().ok()?
        //       .strip_prefix("Bearer ")?;
        //   let claims = jwt::verify(token, &JWT_SECRET).ok()?;
        //   Some(UserClaims {{ user_id: claims.sub, roles: claims.roles, ..Default::default() }})
        None
    }}
}}

// ─── Entry point ─────────────────────────────────────────────────────────────

#[tokio::main]
async fn main() {{
    let auth_state = AuthState {{ validator: Arc::new({pascal}Auth) }};
    let app_state = AppState {{ auth: auth_state, guards: Arc::new(vec![]) }};

    // Register applets — name becomes the URL prefix.
    // "hello" → all routes inside hello.applet mount under /hello
    let app = SweechApp::new()
        .applet(Applet::new(
            AppletConfig::new("hello").default_auth(AuthRequirement::Public),
            AppletRouter::new().register::<Hello>("/"),
            app_state,
        ))
        .build();

    let port = std::env::var("PORT").unwrap_or_else(|_| "3000".to_string());
    let addr = format!("0.0.0.0:{{}}", port);
    let listener = TcpListener::bind(&addr).await.unwrap();
    println!("→ sweech listening on http://{{}}", addr);
    sweech_axum::serve(listener, app).await.unwrap();
}}
"#
    )
}

pub fn hello_route_rs() -> String {
    r#"use sweech_core::prelude::*;

#[derive(Deserialize)]
pub struct HelloRequest {}

#[derive(Serialize)]
pub struct HelloResponse {
    pub message: String,
}

pub struct Hello;

#[async_trait]
impl Handler for Hello {
    type Request = HelloRequest;
    type Response = HelloResponse;

    fn method() -> HttpMethod {
        HttpMethod::Get
    }

    fn auth() -> AuthRequirement {
        AuthRequirement::Public
    }

    async fn call(_req: Self::Request, _ctx: AppletContext) -> AppletResponse<Self::Response> {
        AppletResponse::ok(HelloResponse {
            message: "Hello from Sweech!".to_string(),
        })
    }
}
"#
    .to_string()
}

pub fn gitignore() -> &'static str {
    "/target\n.env\n.env.local\n"
}

// ─── sweech add applet templates ─────────────────────────────────────────────

pub fn applet_route_rs(applet_name: &str, auth: &AuthSetting) -> String {
    let pascal = to_pascal_case(applet_name);
    let auth_str = match auth {
        AuthSetting::Required => "AuthRequirement::Required",
        AuthSetting::Public => "AuthRequirement::Public",
        AuthSetting::Optional => "AuthRequirement::Optional",
    };

    format!(
        r#"use sweech_core::prelude::*;

#[derive(Deserialize)]
pub struct {pascal}Request {{}}

#[derive(Serialize)]
pub struct {pascal}Response {{
    // TODO: Add your response fields here
}}

pub struct {pascal};

#[async_trait]
impl Handler for {pascal} {{
    type Request = {pascal}Request;
    type Response = {pascal}Response;

    fn method() -> HttpMethod {{
        HttpMethod::Get
    }}

    fn auth() -> AuthRequirement {{
        {auth_str}
    }}

    async fn call(_req: Self::Request, _ctx: AppletContext) -> AppletResponse<Self::Response> {{
        // TODO: Implement handler logic
        AppletResponse::ok({pascal}Response {{}})
    }}
}}
"#
    )
}

// ─── sweech add handler templates ────────────────────────────────────────────

pub fn handler_route_rs(handler_name: &str, method: &str, auth: &AuthSetting) -> String {
    let pascal = to_pascal_case(handler_name);
    let method_variant = match method.to_uppercase().as_str() {
        "GET" => "HttpMethod::Get",
        "POST" => "HttpMethod::Post",
        "PUT" => "HttpMethod::Put",
        "PATCH" => "HttpMethod::Patch",
        "DELETE" => "HttpMethod::Delete",
        _ => "HttpMethod::Get",
    };
    let auth_str = match auth {
        AuthSetting::Required => "AuthRequirement::Required",
        AuthSetting::Public => "AuthRequirement::Public",
        AuthSetting::Optional => "AuthRequirement::Optional",
    };

    format!(
        r#"use sweech_core::prelude::*;

#[derive(Deserialize)]
pub struct {pascal}Request {{
    // TODO: Add request fields (body for POST/PUT/PATCH, empty for GET/DELETE)
}}

#[derive(Serialize)]
pub struct {pascal}Response {{
    // TODO: Add response fields
}}

pub struct {pascal};

#[async_trait]
impl Handler for {pascal} {{
    type Request = {pascal}Request;
    type Response = {pascal}Response;

    fn method() -> HttpMethod {{
        {method_variant}
    }}

    fn auth() -> AuthRequirement {{
        {auth_str}
    }}

    async fn call(_req: Self::Request, _ctx: AppletContext) -> AppletResponse<Self::Response> {{
        // TODO: Implement handler logic
        AppletResponse::ok({pascal}Response {{}})
    }}
}}
"#
    )
}

// ─── Dockerfile templates ─────────────────────────────────────────────────────

pub fn dockerfile_monolith_rust_only(project_name: &str, port: u16) -> String {
    format!(
        r#"# syntax=docker/dockerfile:1
# ── Stage 1: Build ───────────────────────────────────────────────────────────
FROM rust:1.77-slim AS builder

WORKDIR /app

# Cache dependency layers: copy manifests first, then source
COPY Cargo.toml Cargo.lock ./
COPY {project_name}-app/Cargo.toml ./{project_name}-app/

# Build a dummy main to cache deps
RUN mkdir -p {project_name}-app/src && \
    echo 'fn main() {{}}' > {project_name}-app/src/main.rs && \
    cargo build --release --manifest-path {project_name}-app/Cargo.toml && \
    rm -rf {project_name}-app/src

# Now copy real source and applets
COPY {project_name}-app/ ./{project_name}-app/
COPY *.applet/ ./

# Touch to force rebuild of the final binary
RUN touch {project_name}-app/sweech.app.rs && \
    cargo build --release --manifest-path {project_name}-app/Cargo.toml

# ── Stage 2: Runtime ──────────────────────────────────────────────────────────
FROM debian:bookworm-slim AS runtime

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=builder /app/target/release/{project_name} ./sweech-app

ENV PORT={port}
EXPOSE {port}

CMD ["./sweech-app"]
"#
    )
}

pub fn dockerfile_monolith_embedded_frontend(
    project_name: &str,
    port: u16,
    frontend_path: &str,
    build_command: &str,
) -> String {
    // Split "npm run build" into ["npm", "run", "build"] for RUN
    format!(
        r#"# syntax=docker/dockerfile:1
# ── Stage 1: Build frontend ───────────────────────────────────────────────────
FROM node:20-slim AS frontend-builder

WORKDIR /frontend
COPY {frontend_path}/package*.json ./
RUN npm ci
COPY {frontend_path}/ ./
RUN {build_command}

# ── Stage 2: Build backend ────────────────────────────────────────────────────
FROM rust:1.77-slim AS backend-builder

WORKDIR /app
COPY Cargo.toml Cargo.lock ./
COPY {project_name}-app/Cargo.toml ./{project_name}-app/

RUN mkdir -p {project_name}-app/src && \
    echo 'fn main() {{}}' > {project_name}-app/src/main.rs && \
    cargo build --release --manifest-path {project_name}-app/Cargo.toml && \
    rm -rf {project_name}-app/src

COPY {project_name}-app/ ./{project_name}-app/
COPY *.applet/ ./
RUN touch {project_name}-app/sweech.app.rs && \
    cargo build --release --manifest-path {project_name}-app/Cargo.toml

# ── Stage 3: Runtime ──────────────────────────────────────────────────────────
FROM debian:bookworm-slim AS runtime

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY --from=backend-builder /app/target/release/{project_name} ./sweech-app
# Static assets served by the backend at /api/* (api) + /* (frontend)
COPY --from=frontend-builder /frontend/out ./public

ENV PORT={port}
EXPOSE {port}

CMD ["./sweech-app"]
"#
    )
}

pub fn dockerignore() -> &'static str {
    "target/\n.git/\n.env\n.env.local\nnode_modules/\n"
}

pub fn docker_compose_monolith(project_name: &str, port: u16) -> String {
    format!(
        r#"services:
  {project_name}:
    build: .
    ports:
      - "{port}:{port}"
    environment:
      - PORT={port}
      - DATABASE_URL=${{DATABASE_URL}}
      - JWT_SECRET=${{JWT_SECRET}}
    restart: unless-stopped
"#
    )
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

/// Convert snake_case or kebab-case to PascalCase.
///   "get_products" → "GetProducts"
///   "create-item"  → "CreateItem"
///   "hello"        → "Hello"
pub fn to_pascal_case(s: &str) -> String {
    s.split(|c| c == '_' || c == '-')
        .filter(|p| !p.is_empty())
        .map(|p| {
            let mut chars = p.chars();
            match chars.next() {
                None => String::new(),
                Some(first) => first.to_uppercase().to_string() + chars.as_str(),
            }
        })
        .collect()
}

/// Infer the framework-appropriate package manager from a project path.
/// Falls back to "npm" if nothing is found.
#[allow(dead_code)]
pub fn detect_package_manager(frontend_path: &std::path::Path) -> &'static str {
    if frontend_path.join("pnpm-lock.yaml").exists() {
        "pnpm"
    } else if frontend_path.join("yarn.lock").exists() {
        "yarn"
    } else {
        "npm"
    }
}

/// Return the default dev command for a given framework, optionally
/// substituting the detected package manager.
#[allow(dead_code)]
pub fn default_dev_command_for(framework: &FrontendFramework, pm: &str) -> String {
    match framework {
        FrontendFramework::Expo => "npx expo start".to_string(),
        FrontendFramework::Ionic => "ionic serve".to_string(),
        _ => format!("{pm} run dev"),
    }
}

// ─── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn pascal_case_from_snake() {
        assert_eq!(to_pascal_case("get_products"), "GetProducts");
        assert_eq!(to_pascal_case("create_item"), "CreateItem");
        assert_eq!(to_pascal_case("hello"), "Hello");
    }

    #[test]
    fn pascal_case_from_kebab() {
        assert_eq!(to_pascal_case("my-applet"), "MyApplet");
    }

    #[test]
    fn handler_route_has_correct_method() {
        let src = handler_route_rs("create_product", "POST", &AuthSetting::Required);
        assert!(src.contains("HttpMethod::Post"));
        assert!(src.contains("pub struct CreateProduct;"));
        assert!(src.contains("type Request = CreateProductRequest;"));
    }
}
