// ─── What is this file? ───────────────────────────────────────────────────────
//
// Generates packages/types/index.ts from the scanned project.
//
// For each route with a parsed HandlerInfo we emit:
//   1. TypeScript interfaces for the Request and Response types
//      (placeholder interfaces — the dev fills in the fields)
//   2. A fully typed API registry object:
//
//      export const API = {
//        inventory: {
//          getItems: {
//            method: "GET",
//            path: "/inventory/items",
//            request: {} as GetItemsRequest,
//            response: {} as GetItemsResponse,
//          },
//          ...
//        }
//      } satisfies ApiRegistry;
//
// The placeholder interfaces use `// TODO` comments so the developer knows
// what to fill in. On subsequent re-runs, existing interfaces are preserved
// (we only add/update the API registry object at the bottom).
//
// Philosophy: this is the developer's source of truth for types.
// Sweech generates the scaffold; the developer owns the field definitions.

use crate::{
    manifest::Manifest,
    scanner::{HandlerInfo, ScannedProject, ScannedRoute},
};
use anyhow::{Context, Result};
use std::{
    collections::HashMap,
    path::{Path, PathBuf},
};

/// Generate packages/types/index.ts.
/// Returns the path to the generated file.
pub fn generate(
    project_root: &Path,
    manifest: &Manifest,
    project: &ScannedProject,
) -> Result<PathBuf> {
    // Collect all routes that have handler info
    let mut routes_with_info: Vec<(&str, &ScannedRoute, &HandlerInfo)> = Vec::new();

    for applet in &project.applets {
        for route in &applet.routes {
            if let Some(info) = &route.handler_info {
                routes_with_info.push((&applet.name, route, info));
            }
        }
    }

    if routes_with_info.is_empty() {
        anyhow::bail!(
            "No handlers with extractable type info found.\n\
             Make sure your route.rs files implement the Handler trait\n\
             with type Request = ... and type Response = ... declarations."
        );
    }

    let out_dir = project_root.join("packages").join("types");
    std::fs::create_dir_all(&out_dir)
        .with_context(|| format!("Could not create {}", out_dir.display()))?;

    let out_path = out_dir.join("index.ts");

    // Read existing file to preserve manually-edited interfaces
    let existing = std::fs::read_to_string(&out_path).unwrap_or_default();

    let content = build_types_file(manifest, &routes_with_info, &existing);

    std::fs::write(&out_path, &content)
        .with_context(|| format!("Failed to write {}", out_path.display()))?;

    Ok(out_path)
}

fn build_types_file(
    _manifest: &Manifest,
    routes: &[(&str, &ScannedRoute, &HandlerInfo)],
    existing: &str,
) -> String {
    let mut out = String::new();

    // ── File header ───────────────────────────────────────────────────────────
    out.push_str("// ─────────────────────────────────────────────────────────────────\n");
    out.push_str("// Auto-generated by `sweech generate types`\n");
    out.push_str("// DO NOT edit the API registry below — it is overwritten on each run.\n");
    out.push_str("// DO edit the interfaces above — they are preserved across runs.\n");
    out.push_str("// ─────────────────────────────────────────────────────────────────\n\n");

    // ── Collect all type names we need ────────────────────────────────────────
    let mut all_types: Vec<String> = Vec::new();
    for (_, _, info) in routes {
        if !all_types.contains(&info.request_type) {
            all_types.push(info.request_type.clone());
        }
        if !all_types.contains(&info.response_type) {
            all_types.push(info.response_type.clone());
        }
    }

    // ── Emit interfaces ───────────────────────────────────────────────────────
    // For each type: if it already exists in the existing file, copy the
    // existing definition. Otherwise emit a placeholder.
    for type_name in &all_types {
        if let Some(existing_def) = extract_existing_interface(existing, type_name) {
            out.push_str(&existing_def);
            out.push('\n');
        } else {
            out.push_str(&placeholder_interface(type_name));
            out.push('\n');
        }
    }

    // ── ApiRegistry type ──────────────────────────────────────────────────────
    out.push_str("// ─── Registry infrastructure ────────────────────────────────────────\n\n");
    out.push_str("export type ApiEndpoint<Req, Res> = {\n");
    out.push_str("  method: \"GET\" | \"POST\" | \"PUT\" | \"PATCH\" | \"DELETE\";\n");
    out.push_str("  path: string;\n");
    out.push_str("  request: Req;\n");
    out.push_str("  response: Res;\n");
    out.push_str("};\n\n");
    out.push_str(
        "// eslint-disable-next-line @typescript-eslint/no-explicit-any\n\
         export type ApiRegistry = Record<string, Record<string, ApiEndpoint<any, any>>>;\n\n",
    );

    // ── API registry object ───────────────────────────────────────────────────
    // Group routes by applet
    let mut by_applet: HashMap<&str, Vec<(&ScannedRoute, &HandlerInfo)>> = HashMap::new();
    for (applet_name, route, info) in routes {
        by_applet
            .entry(applet_name)
            .or_default()
            .push((route, info));
    }

    // Sort applets alphabetically for deterministic output
    let mut applet_names: Vec<&&str> = by_applet.keys().collect();
    applet_names.sort();

    out.push_str("// ─── API registry ────────────────────────────────────────────────────\n\n");
    out.push_str("export const API = {\n");

    for applet_name in &applet_names {
        let applet_routes = &by_applet[*applet_name];
        out.push_str(&format!("  {}: {{\n", applet_name));

        // Sort routes by path for deterministic output
        let mut sorted_routes = applet_routes.clone();
        sorted_routes.sort_by(|a, b| a.0.axum_path.cmp(&b.0.axum_path));

        for (route, info) in &sorted_routes {
            let key = endpoint_key(&info.handler_name);
            let full_path = route.full_path(applet_name);

            out.push_str(&format!("    {}: {{\n", key));
            out.push_str(&format!("      method: \"{}\" as const,\n", info.method));
            out.push_str(&format!("      path: \"{}\" as const,\n", full_path));
            out.push_str(&format!("      request: {{}} as {},\n", info.request_type));
            out.push_str(&format!(
                "      response: {{}} as {},\n",
                info.response_type
            ));
            out.push_str("    },\n");
        }

        out.push_str("  },\n");
    }

    out.push_str("} satisfies ApiRegistry;\n");

    // ── Helper type for frontend consumers ───────────────────────────────────
    out.push('\n');
    out.push_str("// Derive request/response types from the registry\n");
    out.push_str("export type RequestOf<\n");
    out.push_str("  A extends keyof typeof API,\n");
    out.push_str("  E extends keyof (typeof API)[A]\n");
    out.push_str(
        "> = (typeof API)[A][E] extends ApiEndpoint<infer Req, unknown> ? Req : never;\n\n",
    );
    out.push_str("export type ResponseOf<\n");
    out.push_str("  A extends keyof typeof API,\n");
    out.push_str("  E extends keyof (typeof API)[A]\n");
    out.push_str("> = (typeof API)[A][E] extends ApiEndpoint<unknown, infer Res> ? Res : never;\n");

    out
}

/// Generate a placeholder TypeScript interface with TODO comments.
fn placeholder_interface(type_name: &str) -> String {
    // Request types get an empty body hint; Response types get a data hint
    let is_request = type_name.ends_with("Request");
    let body = if is_request {
        "  // TODO: Add request fields (leave empty for GET/DELETE routes)\n"
    } else {
        "  // TODO: Add response fields\n"
    };

    format!("export interface {} {{\n{}}}\n", type_name, body)
}

/// Try to extract an existing interface definition from a previously
/// generated file. Returns the full `export interface Foo { ... }` block.
fn extract_existing_interface(source: &str, type_name: &str) -> Option<String> {
    let start_marker = format!("export interface {} {{", type_name);
    let start = source.find(&start_marker)?;

    // Find the matching closing brace (simple brace counting)
    let slice = &source[start..];
    let mut depth = 0;
    let mut end = 0;

    for (i, ch) in slice.char_indices() {
        match ch {
            '{' => depth += 1,
            '}' => {
                depth -= 1;
                if depth == 0 {
                    end = i + 1;
                    break;
                }
            }
            _ => {}
        }
    }

    if end == 0 {
        return None;
    }

    Some(slice[..end].to_string() + "\n")
}

/// Convert a PascalCase handler name to a camelCase endpoint key.
///   "GetProducts"  → "getProducts"
///   "CreateItem"   → "createItem"
///   "DeleteById"   → "deleteById"
fn endpoint_key(handler_name: &str) -> String {
    let mut chars = handler_name.chars();
    match chars.next() {
        None => String::new(),
        Some(first) => first.to_lowercase().to_string() + chars.as_str(),
    }
}

// ─── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn endpoint_key_conversion() {
        assert_eq!(endpoint_key("GetProducts"), "getProducts");
        assert_eq!(endpoint_key("CreateItem"), "createItem");
        assert_eq!(endpoint_key("DeleteById"), "deleteById");
    }

    #[test]
    fn placeholder_interface_request() {
        let s = placeholder_interface("GetProductsRequest");
        assert!(s.contains("export interface GetProductsRequest"));
        assert!(s.contains("TODO"));
    }

    #[test]
    fn extract_existing_interface_works() {
        let source = r#"
export interface GetProductsRequest {
  // leave empty
}

export interface GetProductsResponse {
  products: Product[];
  total: number;
}
"#;
        let extracted = extract_existing_interface(source, "GetProductsResponse").unwrap();
        assert!(extracted.contains("products: Product[]"));
        assert!(extracted.contains("total: number"));
    }

    #[test]
    fn extract_missing_returns_none() {
        let source = "export interface Foo {}\n";
        assert!(extract_existing_interface(source, "Bar").is_none());
    }

    #[test]
    fn build_types_has_registry() {
        use crate::scanner::{HandlerInfo, ScannedRoute};
        use std::path::PathBuf;

        let info = HandlerInfo {
            handler_name: "GetItems".to_string(),
            request_type: "GetItemsRequest".to_string(),
            response_type: "GetItemsResponse".to_string(),
            method: "GET".to_string(),
        };
        let route = ScannedRoute {
            path_segments: vec!["items".to_string()],
            file: PathBuf::from("inventory.applet/items/route.rs"),
            axum_path: "/items".to_string(),
            handler_info: Some(info.clone()),
        };

        let manifest: crate::manifest::Manifest = toml::from_str(
            r#"[project]
name = "test"
[build]
mode = "monolith"
"#,
        )
        .unwrap();

        let routes = vec![("inventory", &route, &info)];
        let output = build_types_file(&manifest, &routes, "");

        assert!(output.contains("export interface GetItemsRequest"));
        assert!(output.contains("export interface GetItemsResponse"));
        assert!(output.contains("export const API"));
        assert!(output.contains("inventory:"));
        assert!(output.contains("getItems:"));
        assert!(output.contains("method: \"GET\" as const"));
        assert!(output.contains("path: \"/inventory/items\" as const"));
    }
}
